[Connection]
adapter  = "mysql"
encoding = "utf8"
host = "localhost"
username = "root"
password = "root"

[Databases]
  [Databases.development]
  database = "iroiro"

  [Databases.test]
  database = "iroiro_test"

  [Databases.production]
  database = "iroiro"
