[Connection]
adapter  = "mysql"
encoding = "utf8"
host     = "localhost"
port     = "3306"
username = "root"
password = "root"

[Databases]
  [Databases.development]
  database = "iroiro"

  [Databases.test]
  database = "iroiro_test"

  [Databases.production]
  database = "iroiro"
  host     = "173.194.243.81"
  username = "iroiro"
  password = "7ac2151142599989f18f1c00e06443a24cb39603"
